#!/usr/bin/env python

import argparse 
import sys
import os


def modify_seqmagick_sto_file(input_sto, input_str, output_file):
    """
    1). replace t to u, in sequence
    2). replace gaps - to . in sequence
    3). add #=GC SS_cons row for secondary structure 
    4). replace ( to <, ) to > in #=GC SS_cons field
    5). remove all empty blank after secondary structure
    """
    # get str from RNAalifold result
    structrue = None
    consensus = None
    with open(input_str, "r") as ih:
        for line in ih:
            if "A" in line:
                consensus = line.strip().replace("_", ".")
            elif "(" in line or ")" in line:
                line = line.split(" ", 1)[0].strip().replace("(", "<").replace(")", ">")
                structrue = line
                break

    # modify
    with open(input_sto, "r") as ih, open(output_file, "w") as oh:
        for line in ih:
            # no change
            if line.startswith("#"):
                oh.write(line)
            # add str
            elif line.startswith("//"):
                oh.write("#=GC SS_cons " + structrue + "\n")
                oh.write("#=GC RF " + consensus + "\n")
                oh.write(line)
            # replace t and - 
            else:
                name, seq = line.strip().split(" ", 1)
                seq = seq.replace("t", 'u').replace("-", ".")
                oh.write(" ".join([name, seq]) + "\n")




def main():
    parser = argparse.ArgumentParser(description="modify sto file generated by seqmagick, to make it suitable for R2R\n")
    parser.add_argument("input_sto", help="input sto file generated by seqmagick")
    parser.add_argument("input_RNAalifold", help="input RNAalifold file")
    parser.add_argument("-o", "--output", required=False, help="output sto file")

    if len(sys.argv) < 2:
        sys.stderr.write("\nERROR: Not enough parameters were provided, please refer to the usage.\n")
        sys.stderr.write(parser.format_help())
        sys.exit(1)

    args = parser.parse_args()
    
    outfile = args.output
    if not outfile:
        outfile = args.input_sto.rsplit(".", 1)[0] + "_for_Rscape.sto"

    # modify
    modify_seqmagick_sto_file(args.input_sto, args.input_RNAalifold, outfile)


if __name__ == "__main__":
    main()
