# transdecoder 
#
# VERSION       latest

FROM shengwei/ubuntu:16.04
MAINTAINER Shengwei Hou, housw2010@gmail.com

# update
RUN chown root:root /tmp && chmod 1777 /tmp
RUN DEBIAN_FRONTEND=noninteractive apt-get -qq update
RUN DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y gcc
RUN DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y make 
RUN DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y build-essential
RUN DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y zlib1g-dev
RUN DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y wget
RUN DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y liburi-escape-xs-perl
RUN DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y cpanminus
RUN DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y ncbi-blast+ 
RUN DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y hmmer
RUN DEBIAN_FRONTEND=noninteractive apt-get clean

# perl lib
RUN cpanm URI::Escape

# variables
ENV TRANSDECODER_DIR /transdecoder
ENV VERSION v5.3.0
RUN mkdir $TRANSDECODER_DIR
WORKDIR $TRANSDECODER_DIR

# install from github
RUN wget https://github.com/TransDecoder/TransDecoder/archive/TransDecoder-${VERSION}.tar.gz
RUN tar zxfv TransDecoder-${VERSION}.tar.gz
RUN rm TransDecoder-${VERSION}.tar.gz
RUN ln -s TransDecoder-TransDecoder-${VERSION} current

# add to PATH 
ENV PATH="$PATH":$TRANSDECODER_DIR/current:$TRANSDECODER_DIR/current/util

# install miniconda3
RUN apt-get -qq update && apt-get -qq -y install vim curl bzip2 \ 
    && curl -sSL https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -o /tmp/miniconda.sh \ 
    && bash /tmp/miniconda.sh -b -u -p /anaconda \
    && rm -rf /tmp/miniconda.sh
ENV PATH /anaconda/bin:$PATH

# install diamond 
RUN conda config --add channels conda-forge
RUN conda config --add channels bioconda
RUN conda install -c bioconda diamond --yes
RUN conda install -c bioconda pfam_scan --yes
RUN conda clean --all --yes

# Entry
VOLUME /mnt
WORKDIR /mnt
CMD [ "/bin/bash" ]

